name: OpenAPI Diff
on:
  pull_request:
    branches:
      - "**"
jobs:
  diff:  
    name: Realize diff between two files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo ${{ github.repository }}
          echo ${{ github.ref_name }}

      - name: Running OpenAPI Spec diff action
        uses: oasdiff/oasdiff-action/diff@main
        with:
            base: 'swagger-apis/automatic-payments/1.0.0-beta.5.yml'
            revision: 'swagger-apis/automatic-payments/1.0.0-beta.6.yml'
            format: text
            fail-on-diff: false
